name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install dependencies
        run: npm ci
      - name: lint code
        run: npm run lint

  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: ['14', '16']
    name: Tests - Node ${{ matrix.node }} (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: install dependencies
        run: npm ci --ignore-engines
      - name: run tests
        run: npm run test
      - name: run code coverage
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  release:
    name: do semantic release
    runs-on: 'ubuntu-latest'
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '24'
      - name: install deps
        run: npm ci
      - name: build CJS artifacts
        run: npm run build
      - name: release
        run: npx semantic-release@latest
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
